server:
  port: 8082
spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/linjiashop?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true